### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by kankaristo** [abe33/atom-tree-view-breadcrumb#13]
I'm not sure if this is a bug in `tree-view-breadcrumb` or `tree-view`.

The "View Issue" button actually directs me here: https://github.com/atom/tree-view/issues/338, but that seems like an entirely different issue.

Here's the stack trace:
```
TypeError: Cannot read property 'top' of undefined
  at TreeView.module.exports.TreeView.scrollToEntry (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:1078:38)
  at tree-view-breadcrumb.BreadcrumbElement.attach (/home/sami/.atom/packages/tree-view-breadcrumb/lib/breadcrumb-element.coffee:93:31)
  at tree-view-breadcrumb.BreadcrumbElement.show (/home/sami/.atom/packages/tree-view-breadcrumb/lib/breadcrumb-element.coffee:81:6)
  at tree-view-breadcrumb.BreadcrumbElement.subscribeToTreeView (/home/sami/.atom/packages/tree-view-breadcrumb/lib/breadcrumb-element.coffee:68:6)
  at /home/sami/.atom/packages/tree-view-breadcrumb/lib/breadcrumb-element.coffee:54:8
```

This comes up from time to time when opening a new Atom window, but not always.

- Atom 0.207.0
- tree-view 0.171.0
- tree-view-breadcrumb 0.6.0
- Ubuntu 14.04.2 LTS

**Comment by abe33** [comment]
@kankaristo no you're at the right place, can you tell me a bit about the context in which it happened, the stack says it occured on attachment, but what was the content of the tree-view at that point, as it seems it can't find a selected element.

**Comment by kankaristo** [comment]
It happens quite rarely, and I can't find a way to reproduce it right now...

I'll collect as much info as I can the next time it happens.

**Comment by abe33** [comment]
My guess is that there' probably no selection in the tree-view when it occurs, but I would like to confirm that if possible.

**Comment by eboracus** [comment]
Yes this does seem to occur when there is no selection in the tree view. At least I've seen it when disabling and then re-enabling the package in the settings view (hence no selection active in the tree view). But when disabling and then re-enabling manually using the config.cson file and with this file selected in the tree view the error doesn't occur. Using config.cson with the file not selected in the tree view (i.e. the .atom/ folder not included as a project folder) the error occurs as before.
