### ISSUE TITLE
Clickable breadcrumb

### ISSUE THREAD

**Issue by eboracus** [abe33/atom-tree-view-breadcrumb#14]
To help with navigation through large directory structures, in addition to the current location finding, I think it could be a nice feature if the individual items in the breadcrumb were clickable and doing so would jump the current location of the main tree-view to that folder.

Also whilst trying to click on different folders in the trail I noticed the horizontal scroll doesn't seem to function so, depending on the 'Scroll To Last Item' setting, the view remains fixed at either the beginning or the end of the path.

**Comment by abe33** [comment]
> To help with navigation through large directory structures, in addition to the current location finding, I think it could be a nice feature if the individual items in the breadcrumb were clickable and doing so would jump the current location of the main tree-view to that folder.

This is the current behavior, or maybe I don't understand what you mean: 
![breadcrumb-click](https://cloud.githubusercontent.com/assets/247140/8426403/c7f66d14-1f0f-11e5-9954-cf781a1eac8a.gif)

> Also whilst trying to click on different folders in the trail I noticed the horizontal scroll doesn't seem to function so, depending on the 'Scroll To Last Item' setting, the view remains fixed at either the beginning or the end of the path.

Hmm, I'm not sure I fully understand the problem here, can you make me a screencap so that I can see what you're talking about?

**Comment by eboracus** [comment]
Apologies for the confusion, didn't test enough first. It turns out this is a conflict between this package and the [tree-view-background](https://github.com/KoharaKazuya/tree-view-background) package. Trying with that package disabled works perfectly as expected (scroll and click).

Not sure where the specific conflict lies, but it appears the breadcrumb path is appearing 'behind' the background image generated by the other package. As I had the image there set pretty transparent, the path was visible but not clickable. Increasing opacity of the background image, which is in front, noting breadcrumb behind, tree view text in front of background:

![breadcrumb_background2](https://cloud.githubusercontent.com/assets/11758299/8459334/5fea9a78-2014-11e5-8806-0cddfbabdea7.gif)

Is it feasible to have the background/foreground 'order' of the breadcrumb path be brought forward to match the position of the main tree view file system? As in the example above there is no issue clicking the '.log' & 'version.ini' files.

I can open open an issue on tree-view-background if the problem lies there.

**Comment by abe33** [comment]
You can probably play with the elements z-index to make the breadcrumb appear above the rest.
Originally the breadcrumb is not overlayed above the tree-view but is just appended in the `tree-view-resizer` (iirc) and affect the flex-box flow. I don't really now how `tree-view-background` works but a z-index should be enough.

Let me know if it solves things for you.

**Comment by eboracus** [comment]
Excellent, thanks for the info. Altering the index on this package had no effect on the order, the `tree-view-background` package specified no z-index explicitly so maybe that's why(?) Anyway I added an explicit index to ensure it remained at the back and all now works perfectly these two packages can co-exist it seems... awesome :sunglasses:

**Comment by abe33** [comment]
Thanks for the feedback, I'll close this issue then.
