### ISSUE TITLE
Request: display project root name

### ISSUE THREAD

**Issue by jasesmith** [abe33/atom-tree-view-breadcrumb#21]
This is totally a non-issue, but a feature request: a setting to show the project root name _along with (or instead of) the project root folder/icon_.

When working with fullscreen mode (mac) with multiple projects open (which creates multiple "desktops" to slide to), I cannot readily tell which project I'm on. The mac fullscreen mode removes Atom's application title bar from view to maximize vertical screen space. Here's a screen grab of one of my desktops with Atom open in fullscreen mode, and the only way to confirm which project I'm in is to scroll the file tree to the top to see the project root name, or bump my mouse up to the top of the screen and wait for OS X to slide the title bar down, and then visually parse the current file path to find the project name (not ideal).
 
![image](https://cloud.githubusercontent.com/assets/1619521/10341408/c8b44c84-6cd1-11e5-900a-12f9827886e8.png)

Thanks for making some truly great Atom packages!

**Comment by abe33** [comment]
Hi @jasesmith, thanks for the suggestion, it totally make sense so I'll try to find some time to work on that.

**Comment by jasesmith** [comment]
Awesome! Thanks so much.

**Comment by jasesmith** [comment]
Wow, thank you so much for the quick response! It works great!
