### ISSUE TITLE
current selection can be invisible in marginal case

### ISSUE THREAD

**Issue by cognominal** [abe33/atom-tree-view-breadcrumb#7]
When descending a large treeview with the down arrow, the selection eventually becomes invisible.
I suppose that the treeview is unaware of your package and acts like you breadcrumb was
not active and get a wrong visible height. Indeed the visible height is diminshed by the breadcrumbs.

**Comment by kankaristo** [comment]
I'm not sure if this is a proper way to fix this, but it works for me. :)

I added this to my `styles.less`:
```
ol.tree-view li.directory.project-root:last-child {
  padding-bottom: 20px;
}
```

**Comment by abe33** [comment]
Wow, sorry guys, I had completely forgotten about that issue. I'll try to see if I can find some time for that.
