### ISSUE TITLE
Doesn't appear to work as of Atom 166

### ISSUE THREAD

**Issue by paradox460** [abe33/atom-tree-view-breadcrumb#8]
Previously this extension has worked fine, but now it doesn't show up.

Atom 166, Mac OS X 10.10.1, extension v0.3.0

**Comment by abe33** [comment]
Works fine for me can you provide some more informations? 
Is there some message in the console or something?

**Comment by paradox460** [comment]
Interestingly enough, no. It seemed to be working flawlessly before the update, and now it doesn’t appear anywhere on my status bar. There are no warnings.

**Comment by abe33** [comment]
> and now it doesn’t appear anywhere on my status bar

It never appeared in the status bar? Are you sure you're not mistaking this package with another?

**Comment by paradox460** [comment]
Disregard everything. Restarting Atom made it suddenly appear. Guess it was an id10t error.

Thanks!
