### ISSUE TITLE
Showing and hiding of tree view gives error

### ISSUE THREAD

**Issue by DavidLGoldberg** [abe33/atom-tree-view-breadcrumb#9]
Restart atom where tree view is open.  cmd + \ to close, and once again to open gives the following error (but only pops up the first time)

Uncaught TypeError: Cannot read property 'scrollTop' of null
/Users/dgoldberg/.atom/packages/tree-view-breadcrumb/lib/breadcrumb-element.coffee:134
Hide Stack Trace
TypeError: Cannot read property 'scrollTop' of null
  at tree-view-breadcrumb.BreadcrumbElement.update (/Users/dgoldberg/.atom/packages/tree-view-breadcrumb/lib/breadcrumb-element.coffee:134:34)
  at /Users/dgoldberg/.atom/packages/tree-view-breadcrumb/lib/breadcrumb-element.coffee:130:8
The error was thrown from the tree-view-breadcrumb package You can help by creating an issue. Please explain what actions triggered this error.

**Comment by abe33** [comment]
Thanks for the report, I'll try to ind a fix for that asap.

**Comment by DavidLGoldberg** [comment]
Hey @abe33 issue #10  is the same issue, but this time the auto issue creator worked :)

**Comment by abe33** [comment]
Ok thanks
